### ISSUE TITLE
compatibilit with mbed 5 and 6

### ISSUE THREAD

**Issue by douardda** [AGlass0fMilk/mbed-mcuboot-demo#3]
the mbed-os.lib targets 7482462434d5cf718177653ef797547a976a7c5e which is mbed-os-5.13.0 but some of the code (when serial-bootloader-enable is set) is mbed 6 only (uses the BufferedSerial class).

**Comment by AGlass0fMilk** [comment]
@douardda Let me know if this is still an issue now that #6 has been merged.

**Comment by douardda** [comment]
I'll give a try ASAP

**Comment by AGlass0fMilk** [comment]
Hi @douardda, I will close this issue for now. If you have issues again please reopen or create a new issue.

Thanks!
