### ISSUE TITLE
Use upstream mcuboot repo

### ISSUE THREAD

**Issue by boraozgen** [AGlass0fMilk/mbed-mcuboot-demo#9]
Hi George,

Thanks for the hard work on the port. Works like a charm on NUCLEO_F429ZI with an external SPI flash with minor changes. My main issue was that your mcuboot fork is outdated. I noticed that most of your changes are already merged to upstream. It also seems to work with upstream master. Would you like to update the lib file?

An issue with the outdated version is that EC256 signatures are not supported with MbedTLS. This was added later.

**Comment by AGlass0fMilk** [comment]
@boraozgen Yes, this demo originally required using some code that was not yet merged into upstream mcuboot. It should be updated to use the main mcuboot branch now.

One thing that prevents this currently is the use of the feature I implemented for MCUboot to get the version of the application (see https://github.com/mcu-tools/mcuboot/pull/863)

This can be easily removed from the demo application and then the upstream mcuboot branch can be used. I would welcome you to contribute any updates to the MbedOS port of mcuboot directly to the mcuboot repository (eg: enabling EC256 and other features).

I am really busy right now working on [Mbed-OS BLE FOTA updates](https://github.com/ARMmbed/mbed-os-experimental-ble-services/issues/46) using this, so I don't have the time at the moment to improve the mcuboot port.

**Comment by boraozgen** [comment]
The port itself works fine, also with EC256, when the latest Mcuboot branch is used.
